const {test,after}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const b=require('../lib/booking');
const book=require('../api/book');
const availability=require('../api/availability');
const oauth=require('../api/oauth');
const originalFetch=global.fetch;
after(()=>{global.fetch=originalFetch});
function setup(){Object.assign(process.env,{GOOGLE_CLIENT_ID:'test',GOOGLE_CLIENT_SECRET:'test',BOOKING_ADMIN_SECRET:'a'.repeat(32),BOOKING_ENCRYPTION_KEY:Buffer.alloc(32,1).toString('base64'),UPSTASH_REDIS_REST_URL:'https://redis.test',UPSTASH_REDIS_REST_TOKEN:'test'});}
function nextMonday(){const d=new Date();d.setUTCDate(d.getUTCDate()+7);while(d.getUTCDay()!==1)d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function request(body){return {method:'POST',url:'/api/book',body,headers:{origin:b.ORIGIN,'x-forwarded-for':'127.0.0.1'}}}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v},end(text){this.body=JSON.parse(text)}}}
function payload(){return {date:nextMonday(),time:'09:00',name:'Cliente Teste',phone:'11999999999',email:'cliente@example.com',requestId:crypto.randomUUID()}}
function mock({busy=[],insertStatus=200,brokenBusy=false}={}){const store=new Map([[b.TOKEN_KEY,b.seal({email:b.OWNER,refreshToken:'test-refresh'})]]);let inserts=0;const events=new Map();global.fetch=async(url,options={})=>{url=String(url);const result=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});if(url==='https://redis.test'){const [cmd,...args]=JSON.parse(options.body);let value=null;if(cmd==='GET')value=store.get(args[0])||null;if(cmd==='MGET')value=args.map(k=>store.get(k)||null);if(cmd==='SET'){if(args.includes('NX')&&store.has(args[0]))value=null;else{store.set(args[0],args[1]);value='OK'}}if(cmd==='GETDEL'){value=store.get(args[0])||null;store.delete(args[0])}if(cmd==='EVAL'){if(args[0].includes('INCR'))value=1;else if(store.get(args[2])===args[3]){store.delete(args[2]);value=1}else value=0;}return result({result:value});}if(url.includes('oauth2.googleapis.com/token'))return result({access_token:'test-access'});if(url.endsWith('/freeBusy'))return result({calendars:{[b.OWNER]:brokenBusy?{errors:[{reason:'forbidden'}]}:{busy}}});if(url.includes('/events?')){inserts++;const event=JSON.parse(options.body);if(insertStatus===200)events.set(event.id,event);return result(insertStatus===200?event:{error:'failed'},insertStatus);}if(url.includes('/events/')){const id=url.split('/').at(-1);return events.has(id)?result(events.get(id)):result({error:'notFound'},404);}throw Error('Unexpected request');};return {store,get inserts(){return inserts}}}
test('dates, schedule and minimum notice are validated on server',()=>{setup();assert.throws(()=>b.dateSlots('2026-02-30'));assert.throws(()=>b.dateSlots('bad'));const slots=b.dateSlots(nextMonday());assert.equal(slots.length,4);assert.equal(new Date(slots[0].end)-new Date(slots[0].start),90*60000);assert.equal(slots[0].start.slice(11,16),'12:00');assert.throws(()=>book.validate({...payload(),time:'09:15'}));assert.throws(()=>book.validate({...payload(),email:'invalid'}));});
test('interval overlap includes partial conflicts and allows adjacent slots',()=>{const s={start:'2030-01-01T12:00:00Z',end:'2030-01-01T13:30:00Z'};assert.equal(b.overlaps(s,[{start:'2030-01-01T13:00:00Z',end:'2030-01-01T14:00:00Z'}]),true);assert.equal(b.overlaps(s,[{start:s.end,end:'2030-01-01T15:00:00Z'}]),false);});
test('encrypted connection detects tampering',()=>{setup();const value=b.seal({refreshToken:'secret'});assert.equal(b.unseal(value).refreshToken,'secret');const bytes=Buffer.from(value,'base64');bytes[30]^=1;assert.throws(()=>b.unseal(bytes.toString('base64')));});
test('missing setup fails closed without a reservation',async()=>{setup();delete process.env.GOOGLE_CLIENT_ID;const res=response();await book(request(payload()),res);assert.equal(res.statusCode,503);assert.equal(res.body.confirmed,undefined);});
test('cross-origin booking denied',async()=>{setup();const req=request(payload());req.headers.origin='https://attacker.example';const res=response();await book(req,res);assert.equal(res.statusCode,403);});
test('availability exposes only time and availability, not calendar details',async()=>{setup();const m=mock();const date=nextMonday();m.store.set(b.reservationKey(date,'09:00'),'pending');const res=response();await availability({method:'GET',url:`/api/availability?date=${date}`,headers:{}},res);assert.equal(res.statusCode,200);assert.equal(res.body.slots[0].available,false);assert.deepEqual(Object.keys(res.body.slots[0]),['time','available']);});
test('calendar permission error never returns free slots',async()=>{setup();mock({brokenBusy:true});const res=response();await availability({method:'GET',url:`/api/availability?date=${nextMonday()}`,headers:{}},res);assert.equal(res.statusCode,503);assert.equal(res.body.slots,undefined);});
test('concurrent clients produce only one event for a slot',async()=>{setup();const m=mock(),r1=response(),r2=response();await Promise.all([book(request(payload()),r1),book(request(payload()),r2)]);assert.deepEqual([r1.statusCode,r2.statusCode].sort(),[201,409]);assert.equal(m.inserts,1);});
test('retry with same request returns confirmed event without duplicate',async()=>{setup();const m=mock(),data=payload(),r1=response(),r2=response();await book(request(data),r1);await book(request(data),r2);assert.equal(r2.statusCode,200);assert.equal(m.inserts,1);});
test('uncertain insert failure retains slot and does not confirm',async()=>{setup();const m=mock({insertStatus:500}),data=payload(),res=response();await book(request(data),res);assert.equal(res.statusCode,503);assert.ok(m.store.has(b.reservationKey(data.date,data.time)));assert.equal(res.body.confirmed,undefined);});
test('OAuth callback rejects missing state/cookie',async()=>{setup();mock();const res=response();await oauth({method:'GET',url:'/api/oauth?action=callback&code=evil',headers:{}},res);assert.equal(res.statusCode,403);});
