const crypto = require('node:crypto');

const OWNER = (process.env.BOOKING_OWNER_EMAIL || 'pedrosolopes.tiago@gmail.com').trim().toLowerCase();
const ORIGIN = 'https://ocorporesponde.vercel.app';
const ZONE = 'America/Sao_Paulo';
const HOURS = {1:['09:00','10:30','14:00','15:30'],2:['09:00','10:30','14:00','15:30'],3:['09:00','10:30','14:00','15:30'],4:['09:00','10:30','14:00','15:30'],5:['09:00','10:30','14:00']};
const DURATION = 90;
const SCOPES = ['openid','email','https://www.googleapis.com/auth/calendar.events','https://www.googleapis.com/auth/calendar.freebusy'];
const ACCOUNT_KEY = crypto.createHash('sha256').update(OWNER).digest('hex').slice(0,24);
const TOKEN_KEY = `ocr:google:connection:`+ACCOUNT_KEY;
class BookingError extends Error { constructor(status, message) { super(message); this.status=status; } }
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
function configured() { return ['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','BOOKING_ADMIN_SECRET','BOOKING_ENCRYPTION_KEY','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'].every(k=>Boolean(process.env[k])) && Buffer.from(process.env.BOOKING_ENCRYPTION_KEY,'base64').length===32 && process.env.BOOKING_ADMIN_SECRET.length>=32; }
function requireConfig() { if(!configured()) throw new BookingError(503,'A agenda on-line ainda não está conectada. Fale conosco pelo WhatsApp.'); }
function seal(data) { const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',Buffer.from(process.env.BOOKING_ENCRYPTION_KEY,'base64'),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(data),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64'); }
function unseal(value) { const data=Buffer.from(value,'base64'),decipher=crypto.createDecipheriv('aes-256-gcm',Buffer.from(process.env.BOOKING_ENCRYPTION_KEY,'base64'),data.subarray(0,12));decipher.setAuthTag(data.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(data.subarray(28)),decipher.final()]).toString('utf8')); }
async function redis(...command) { const response=await fetch(process.env.UPSTASH_REDIS_REST_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.UPSTASH_REDIS_REST_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(8000)});const data=await response.json();if(!response.ok||data.error)throw new BookingError(503,'Não foi possível acessar a agenda. Tente novamente.');return data.result; }
async function googleRequest(url, options={}) { const response=await fetch(url,{...options,signal:AbortSignal.timeout(10000)});const data=await response.json();return {response,data}; }
async function accessToken() { requireConfig();const stored=await redis('GET',TOKEN_KEY);if(!stored)throw new BookingError(503,'A agenda on-line ainda não está conectada. Fale conosco pelo WhatsApp.');const connection=unseal(stored);if(connection.email!==OWNER)throw new BookingError(503,'A conexão da agenda precisa ser revisada.');const {response,data}=await googleRequest('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:connection.refreshToken,grant_type:'refresh_token'})});if(!response.ok||!data.access_token)throw new BookingError(503,'A agenda está temporariamente indisponível. Fale conosco pelo WhatsApp.');return data.access_token; }
async function calendar(path,token,options={}) { return googleRequest(`https://www.googleapis.com/calendar/v3/${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...options.headers}}); }
function dateSlots(date,now=Date.now()) { if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new BookingError(400,'Data inválida.');const day=new Date(`${date}T12:00:00-03:00`);if(!Number.isFinite(day.getTime())||day.toISOString().slice(0,10)!==date)throw new BookingError(400,'Data inválida.');if(day.getTime()>now+90*86400000)throw new BookingError(400,'Escolha uma data nos próximos 90 dias.');return (HOURS[day.getUTCDay()]||[]).map(time=>{const start=new Date(`${date}T${time}:00-03:00`),end=new Date(start.getTime()+DURATION*60000);return {time,start:start.toISOString(),end:end.toISOString(),future:start.getTime()>now+2*3600000};}); }
const overlaps = (slot,busy) => busy.some(b=>new Date(slot.start)<new Date(b.end)&&new Date(slot.end)>new Date(b.start));
async function busyForDate(date,token) { const {response,data}=await calendar('freeBusy',token,{method:'POST',body:JSON.stringify({timeMin:`${date}T00:00:00-03:00`,timeMax:`${date}T23:59:59-03:00`,timeZone:ZONE,items:[{id:OWNER}]})});const result=data.calendars?.[OWNER];if(!response.ok||!result||result.errors?.length)throw new BookingError(503,'Não foi possível consultar os horários. Tente novamente.');return result.busy; }
const reservationKey = (date,time) => `ocr:reservation:${ACCOUNT_KEY}:${date}:${time}`;
function headers(res) { res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer'); }
function json(res,status,data) { headers(res);res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data)); }
function fail(res,error) { json(res,error.status||503,{error:error.status?error.message:'Não foi possível concluir a solicitação. Tente novamente.'}); }
function sameOrigin(req) { if(req.headers.origin!==ORIGIN)throw new BookingError(403,'Origem não autorizada.'); }
async function rateLimit(req,kind,limit) { const ip=String(req.headers['x-forwarded-for']||'unknown').split(',')[0].trim();const digest=crypto.createHmac('sha256',process.env.BOOKING_ADMIN_SECRET).update(ip).digest('hex');const key=`ocr:rate:${kind}:${digest}:${Math.floor(Date.now()/3600000)}`;const count=await redis('EVAL',"local n=redis.call('INCR',KEYS[1]); if n==1 then redis.call('EXPIRE',KEYS[1],3600) end; return n",1,key);if(count>limit)throw new BookingError(429,'Muitas tentativas. Aguarde um pouco antes de tentar novamente.'); }
function parseBody(req) { let body=req.body;if(typeof body==='string'){try{body=JSON.parse(body)}catch{throw new BookingError(400,'Dados inválidos.')}}if(!body||typeof body!=='object'||Array.isArray(body))throw new BookingError(400,'Dados inválidos.');return body; }
module.exports={OWNER,ORIGIN,ZONE,HOURS,DURATION,SCOPES,TOKEN_KEY,BookingError,hash,configured,requireConfig,seal,unseal,redis,googleRequest,accessToken,calendar,dateSlots,overlaps,busyForDate,reservationKey,headers,json,fail,sameOrigin,rateLimit,parseBody};
