const crypto=require('node:crypto');
const b=require('../lib/booking');
const callback=`${b.ORIGIN}/api/oauth?action=callback`;
function redirect(res,url){b.headers(res);res.statusCode=303;res.setHeader('Location',url);res.end();}
module.exports=async(req,res)=>{try{b.requireConfig();const url=new URL(req.url,b.ORIGIN);if(req.method==='POST'){
  b.sameOrigin(req);await b.rateLimit(req,'connect',10);const body=b.parseBody(req);const supplied=String(body.secret||'');if(!crypto.timingSafeEqual(Buffer.from(b.hash(supplied)),Buffer.from(b.hash(process.env.BOOKING_ADMIN_SECRET))))throw new b.BookingError(403,'Código administrativo inválido.');
  const state=crypto.randomBytes(32).toString('hex');await b.redis('SET',`ocr:oauth:${state}`,'1','EX',600);res.setHeader('Set-Cookie',`ocr_oauth=${state}; Path=/api/oauth; HttpOnly; Secure; SameSite=Lax; Max-Age=600`);
  const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:callback,response_type:'code',scope:b.SCOPES.join(' '),state,access_type:'offline',prompt:'consent',login_hint:b.OWNER});b.json(res,200,{url:`https://accounts.google.com/o/oauth2/v2/auth?${params}`});return;
}
if(req.method!=='GET'||url.searchParams.get('action')!=='callback')throw new b.BookingError(405,'Método não permitido.');const state=url.searchParams.get('state')||'',cookie=String(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('ocr_oauth='))?.slice(10);if(!/^[a-f0-9]{64}$/.test(state)||cookie!==state||!(await b.redis('GETDEL',`ocr:oauth:${state}`)))throw new b.BookingError(403,'Autorização expirada. Inicie a conexão novamente.');res.setHeader('Set-Cookie','ocr_oauth=; Path=/api/oauth; HttpOnly; Secure; SameSite=Lax; Max-Age=0');
if(url.searchParams.has('error')){redirect(res,'/conectar-agenda.html?status=cancelado');return;}
const code=url.searchParams.get('code');if(!code)throw new b.BookingError(400,'Autorização incompleta.');const {response,data}=await b.googleRequest('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:callback,grant_type:'authorization_code'})});if(!response.ok||!data.refresh_token||!data.access_token)throw new b.BookingError(400,'Não foi possível conectar. Autorize novamente todas as permissões solicitadas.');
const info=await b.googleRequest('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${data.access_token}`}});if(!info.response.ok||info.data.email!==b.OWNER||!info.data.email_verified)throw new b.BookingError(403,'Use a conta Google do analista indicada na página de conexão.');const granted=new Set((data.scope||'').split(' '));if(!b.SCOPES.filter(s=>s.startsWith('https://www.googleapis.com/auth/calendar')).every(s=>granted.has(s)))throw new b.BookingError(403,'Autorize a consulta de disponibilidade e o gerenciamento de eventos.');
await b.busyForDate(new Date().toISOString().slice(0,10),data.access_token);await b.redis('SET',b.TOKEN_KEY,b.seal({email:b.OWNER,refreshToken:data.refresh_token,connectedAt:new Date().toISOString()}));redirect(res,'/conectar-agenda.html?status=conectado');
}catch(error){b.fail(res,error)}};
